### ISSUE TITLE
BUILD PROJECT

### ISSUE THREAD

**Issue by matheuscamarques** [MaharshSuryawala/Face-Detection-and-Facial-Expression-Recognition#9]
Hello how do build this project ?

**Comment by MaharshSuryawala** [comment]
Hi, Thanks for reaching out. 

You'll be able to find the source code in the Jupyter Notebooks (.ipynb files). Refer to [this](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html) guide in order to execute them. 

Hope this helps!
